### ISSUE TITLE
[Meta] Developer experience improvements

### ISSUE THREAD

**Issue by monacoremo** [PostgREST/postgrest#1671]
Many good ideas are coming together on how we can improve the developer experience,  e.g. in #1666 . Tracking here to work on them step by step:

* [x] integrate coverage into nix tooling (#1694)
* [x] option to preserve temporary dbs and explore them (#1722)
* [x] script to easily run postgrest against a temporary db (#1722)
* [x] run io tests in nix tooling against the incrementally built postgrest, instead of the nix built one (#1673 )
* [ ] run memory tests in nix tooling against the incrementally built postgrest, instead of the nix built one
* [x] autocomplete for postgrest-watch arguments (#1674, #1676)
* [x] have postgrest-watch watch new files also (#1676)
* [ ] accelerate CI by re-enabling caching for the cabal builds
* [x] add a check that runs tests twice against the same db (see https://github.com/PostgREST/postgrest/pull/1663#issuecomment-737900216) (PR: https://github.com/PostgREST/postgrest/pull/1693)
* [x] add docs on the postgrest-* scripts (#1706)
* [x] -O1 for dev builds
* [x] io tests: make the postgrest endpoint dynamic/switch to unix domain sockets by default to allow parallelization (#1704)
* [x] io tests: include https://pypi.org/project/pytest-parallel/ (used xdist for now in #1704)
* [x] io tests: add docs for advanced usage (postgrest-watch postgrest-test-io -k ... etc.) (#1704)

**Comment by wolfgangwalther** [comment]
I took the freedom to split io/memory up in two bullets and mark the io tests as done per the referenced PR.

**Comment by wolfgangwalther** [comment]
Regarding auto-complete for `postgrest-watch`, I found this: https://askubuntu.com/a/854365

Looks fairly simple.

**Comment by monacoremo** [comment]
> Regarding auto-complete for `postgrest-watch`, I found this:

Nice! Should be pretty easy to plug into the shellHook

**Comment by wolfgangwalther** [comment]
>     * [ ]  have postgrest-watch watch new files also

If I remember correctly, you had `-d` and a while loop around it, which broke `CTRL+C`. I just noticed that the exit code of `entr` is 0 when doing `CTRL+C` and 2 when a new file is added.

So something like this (pseudo) should work:

```
do
  entr -d ...
until exitcode = 0
```

**Comment by wolfgangwalther** [comment]
> run memory tests in nix tooling against the incrementally built postgrest, instead of the nix built one

Would the overhead be big to just use the profiled build for all of `build`, `run`, `test-spec`, `test-io` and `test-memory` - so everything that we do in development?

**Comment by steve-chavez** [comment]
Perhaps it'd be worth to look at speeding compile times for development. I've noticed that we have -O2:

https://github.com/PostgREST/postgrest/blob/7d6d0158227d527e5cc334ed7621a7415eff8a4b/postgrest.cabal#L95-L99

According to [ghc docs](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-optimisation.html#o-convenient-packages-of-optimisation-flags), -O2 means "significantly longer compile times". Perhaps we could have a flag that uses -O0?
(not sure if it makes compiling considerably faster though)

**Comment by wolfgangwalther** [comment]
Good point. I was struggling with build times when I tried to setup the nix-based coverage tools, so far.

Do we need a flag, though? Can't we just use -O0 for all tests / development and only build the releases with -O2?

**Comment by monacoremo** [comment]
Added open items from https://github.com/PostgREST/postgrest/pull/1682

**Comment by wolfgangwalther** [comment]
> Do we need a flag, though? Can't we just use -O0 for all tests / development and only build the releases with -O2?

When I run `postgrest-build`, I get this:

```
Build profile: -w ghc-8.8.3 -O1
```

Is this actually an issue? Afaik -O1 is the same as -O0, so there's probably not more to gain.

**Comment by monacoremo** [comment]
Updated based on #1694 and #1704

**Comment by monacoremo** [comment]
Updated based on #1706

**Comment by wolfgangwalther** [comment]
Updated based on #1722.
