### ISSUE TITLE
[dev] Refactoring roadmap

### ISSUE THREAD

**Issue by monacoremo** [PostgREST/postgrest#1804]
With #1793, we've started to process of streamlining the codebase. This is a purely internal concern that will yield no additional features. It will, however:

* ease maintenance
* help with the onboarding of new contributors
* enable quicker implementation of new features
* further increase confidence on correctness 

Next steps include (in no particular order and to be completed)

* [ ] Encapsulate the `Request` modules behind one API
* [ ] Encapsulate the `Query` modules behind on API
* [ ] Carve-out `Response` concerns from `App`, i.a.
* [ ] Stop using `GHC.Show` instances for string conversion
* [ ] Stop using partial functions (ones from `Protolude.Conv`, `unsafeHead` etc.)
* [ ] Improve string handling in Query generation for additional safety and performance
* [ ] ...

**Comment by monacoremo** [comment]
@steve-chavez decision needed!

This works in principle, with some positives and negatives. 

Positives:

* It works. We have a `postgrest-test-doctest` command and it's integrated in CI
* Doctests are quite easy to write and make for great in-module documentation  (see example in the Preferences module)
* Using doctests drives us to create clean, usable module APIs (as would unit tests, but not the integration tests we have)
* Added complexity is quite low - essentially a section in `postgrest.cabal` and a `Main.hs` file. There is no impact on other tests
* We get extra safety through the additional tests

Negatives:

* We won't get coverage out of the doctests, probably ever - this is an inherent limitation of the GHCi based implementation and the fact that GHCi does not support HPC. At least, we will not worsen coverage
* Running the doctests outside nix-shell right now is flaky and I'm not quite sure why. This should be fixable later, in the meantime it takes about 30s extra time in CI

Should we still merge this? I think the benefits outweigh the negatives and recommend yes.

**Comment by steve-chavez** [comment]
`unsafeHead` went away on https://github.com/PostgREST/postgrest/pull/2254

**Comment by steve-chavez** [comment]
> Request: purely parse request, at most taking config into account. `parseRequest :: Wai.Request -> Either RequestError Request

> Plan: Use db structure to validate and plan the request, including embeds. plan :: DbStructure -> Request -> Either PlanError QueryPlan

To do the above, ApiRequest should remove its dependency on DbStructure - which is needed by the variadic logic introduced on https://github.com/PostgREST/postgrest/pull/1603.  

https://github.com/PostgREST/postgrest/blob/6398dd2b328e14e7a08119c0726a73c6baa721b6/src/PostgREST/Request/ApiRequest.hs#L135

After that [findProc](https://github.com/PostgREST/postgrest/blob/6398dd2b328e14e7a08119c0726a73c6baa721b6/src/PostgREST/Request/ApiRequest.hs#L452-L501) and others can be moved to `Plan.hs` and `ApiRequest` will be much cleaner.

I tried to do this on https://github.com/PostgREST/postgrest/pull/2496 but it turned out difficult bc I'm not familiar with the variadic logic. @wolfgangwalther Would be great if you could help with that.

**Comment by steve-chavez** [comment]
I've been thinking about how we transform requests, and seeing the [The Internals of PostgreSQL query processing chapter here](https://www.interdb.jp/pg/pgsql03.html):

```
1. Parser
The parser generates a parse tree from an SQL statement in plain text.

2. Analyzer/Analyser
The analyzer/analyser carries out a semantic analysis of a parse tree and generates a query tree.

3. Rewriter
The rewriter transforms a query tree using the rules stored in the rule system if such rules exist.

4. Planner
The planner generates the plan tree that can most effectively be executed from the query tree.

5. Executor
The executor executes the query via accessing the tables and indexes in the order that was created by the plan tree.
```

It seems:

- Our `ApiRequest` is the `Parser`
- `Analyzer` is really what we call `Plan` now.
- The `Rewriter` concept could be used to further split our `Plan` module, which is getting big. For example `computed relationships` could be thought of as a "rewrite". https://github.com/PostgREST/postgrest/pull/2523 seems like a rewrite too.
- We don't have a `Planner` per se. This is a further optimization that perhaps could be used reduce generated prepared statements, e.g. `select=id,name` could generate the same query as `select=name,id`. Not sure about this.
- `Executor` doesn't make sense for us.

**Comment by steve-chavez** [comment]
> To do the above, ApiRequest should remove its dependency on DbStructure - which is needed by the variadic logic introduced on https://github.com/PostgREST/postgrest/pull/1603.
> The challenge is, that ApiRequest does pass on URL parameters as iPayload, i.e. payload is either the request body or a json produced from the params. ApiRequest needs to split this up and have the params as just a [(Text, Text)] list.

The above continues to be a major challenge and I don't believe it can be done cleanly on Haskell code. It continues to be a blocker for https://github.com/PostgREST/postgrest/pull/1582 every time I tried it.

I believe the only feasible alternative is to parse the URL on SQL code. This would work for variadic and non-variadic payloads:

```sql
-- here "a" would be the variadic parameter
WITH
foo AS (
  SELECT string_to_array(x, '=') AS key_val FROM string_to_table('a=4&b=3&a=5&c=&d=11&d=15', '&') x
),
foo1 AS (
  SELECT key_val[1] as key, to_json(key_val[2]) as val FROM foo
  union all
  SELECT key_val[1] as key, json_agg(key_val[2]) as val from foo where key_val[1] = 'a' group by key 
),
foo2 AS(
  SELECT jsonb_object_agg(key, val) as res FROM foo1
)
SELECT * FROM jsonb_to_record((SELECT res FROM foo2 LIMIT 1)) AS (a int[], b int, c text, d int);

   a   | b | c | d
-------+---+---+----
 {4,5} | 3 |   | 15
```

Then we can remove the variadic logic from ApiRequest. Doing this on SQL may have other benefits later as well, it may be possible to customize parsing the input with a custom function.

**Comment by steve-chavez** [comment]
Continuing the [above](https://github.com/PostgREST/postgrest/issues/1804#issuecomment-1421587440) idea. Our `App.hs` module can be equated to the `TrafficCop` in PostgreSQL https://wiki.postgresql.org/wiki/Backend_flowchart#Main_Query_Flow

**Comment by steve-chavez** [comment]
There are still some pending refactors but overall the structure now is in line with the original comment. Will unpin this issue as it's not urgent anymore. We can now grow the codebase in a more maintainable manner.

**Comment by dbaynard** [comment]
Congratulations — great job!

> - help with the onboarding of new contributors

As a (current) non-contributer I'm willing to help test this.

**Comment by taimoorzaeem** [comment]
`grep -rn "TODO"` shows many modules where the code cleanup and reorganization is needed. With every new feature and fix and refactoring becomes more and more tedious later. I think we should try to remove these `TODOs` in small steps whenever we have some time. Features and fixes are always a priority, but these `TODOs` get in the way whenever I try to work on something new.

**Comment by steve-chavez** [comment]
Compiling needs for our own Prelude:
 
- https://github.com/PostgREST/postgrest/pull/4297#issuecomment-3254261051
